name: kfc_russia_api
description: API for receiving data from KFC Russia. The library has a class with static methods for retrieving data.
version: 1.0.0
repository: https://github.com/Iv2005an/kfc_russia_api

environment:
  sdk: ^3.2.4

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
